[package]
name = "spyparsey"
version = "0.1.0"
authors = ["Adam Ransom"]

[dependencies]
spyparty = { path = "../spyparty-rs" }
error-chain = "0.12.0"
walkdir = "2"
log = "0.4"
stderrlog = "0.4"

[dependencies.clap]
version = "2.32.0"
features = ["yaml"]
